### ISSUE TITLE
Feature: OSD lyric

### ISSUE THREAD

**Issue by kaer** [eonpatapon/gnome-shell-extensions-mediaplayer#192]
Hi!

Days ago I wanted to display OSD lyrics of songs, however I didn't found any integration of this kind for Gnome Shell, I modified a previous version of your media-player extension and put some code to display lyrics of LRC file format, there are many improvements to be done, today I forked your project and will merge the modification when complete.

I was thinking in a separated extension, but your work is well done and to avoid another DBUs client the feature was added.

If you want to integrate this feature in the mainstream code when it is complete talk to me.

**Comment by eonpatapon** [comment]
Hello,

Sorry for the late reply. Let me know how I can check you code before I say yes or no.

Btw, if you plan to make this as a seprate extension it should be simple to integrate with the latest extension because the manager now emits signals for the active player and each player emits signal when song metatada change.

**Comment by JasonLG1979** [comment]
@kaer any progress on this?

**Comment by JasonLG1979** [comment]
Closing this because if inactivity.
