### ISSUE TITLE
Extension not displaying any information

### ISSUE THREAD

**Issue by jp438** [eonpatapon/gnome-shell-extensions-mediaplayer#259]
Recently I have have been having a problem with this extension not displaying any album or track details. The progress bar is also always 0:00/0:00. It does however still show the buttons to control the music and they work perfectly. The play / pause button always shows the play symbol even when the track is playing.

I have tested this with Spotify and Nuvola Player's Google Play and Amazon Music extensions and these all used to work fine with this extension.

**Comment by apmarques** [comment]
This is happening to me too. Found any way to fix it yet?

**Comment by JasonLG1979** [comment]
@jp438 and @apmarques is this still an issue with the latest git?

**Comment by JasonLG1979** [comment]
Spotify has a broken MPRIS2 implementation. See  https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/199

As far as the rest of the apps go I'm going to say either the problem has been fixed in the extension since this report(if it was ever a problem in the extension) or they are upstream bugs as the extension works perfectly with players that do a reasonable job of implementing the MPRIS2 spec correctly.

Generally speaking this extension is very spec compliant and reasonably forgiving of players that are not. If you have a problem with a player feature not working correctly it more than likely a problem with the player not the extension.
