### ISSUE TITLE
Only system menu shows all playlists for rythmbox

### ISSUE THREAD

**Issue by i30817** [eonpatapon/gnome-shell-extensions-mediaplayer#278]
If you choose right positioning for example, all the lists don't appear (only play queue).

I believe this is probably some cache misbehaving that doesn't exist when the app is embedded directly on the system menu for some reason.

**Comment by badcel** [comment]
What do you experience exactly? As far as i know the play queue should not be displayed at all, but only the playlists.

Are you using the latest version from github?

**Comment by i30817** [comment]
It happens when one starts rythmbox from the right positioning applet, not when it's already running and you happen to switch from the system menu to right on the tweak tool. As i said, i suspect a race or a cache problem during startup.

As for the version, i'm simply using the latest from this page. https://extensions.gnome.org/extension/55/media-player-indicator/

I dont know of a good way to tell the version.

**Comment by i30817** [comment]
Ah i checked the metadata.json now. It says it's 
  "version": 41

**Comment by badcel** [comment]
There was a recent commit which should make the playlist interface more robust: 2184234d15df4be8423d0d55c05e922d01db4bde

For testing purposes you could download the source code of the extension from github and replace it in your extension folder under "~/.local/share/gnome-shell/extensions/mediaplayer@patapon.info". Probably you won't touch the metadata file, so that gnome-shell can check for newer versions.

**Comment by i30817** [comment]
Too troublesome, the source needs compiling and has dependencies. I'll just wait for the new version.

**Comment by i30817** [comment]
Well, nvm, i finally looked at the readme page and noticed i don't need git GNOME. With latest, it worked the first time, didn't work on others. That is, the first time after install and restarting the shell it showed the playlists, then when i killed rhytmbox, it only showed 'Play Queue' (that is empty to boot. Shouldn't this filter out empty playlists?).

Seems like a very fragile protocol.

**Comment by badcel** [comment]
Actually the protocoll is robust. As far as I see it, in most cases it is a problem of the player.

The extension is not supposed to filter any data, because the mpris playlist interface does not deliver any information about the content of the playlists. See https://specifications.freedesktop.org/mpris-spec/latest/Playlists_Interface.html

For me Rhythmbox works since the commit I mentioned. If you are  into this topic the next step would be to check out what is going wrong in code. So you could go into the source directory (see above) and add some Log statements like: log("My log statement");

To see your log statements you could check out your journal with "journalctl -f"

The commit I mentioned added a small timeout before the playlists are loaded from the player. Perhaps in your case the timeout is just to small? You could try to increase the value.

**Comment by JasonLG1979** [comment]
To expand on what @badcel said. The MediaPlayer2.Playlists and MediaPlayer2.TrackList interfaces are separate and can be implemented independent of each other. AFAIK this extension does not support the MediaPlayer2.TrackList interface ATM. The Playlist interface allows you to view and change playlists from the client(in this case this extension) and that's about it. There is also the possibility of sorting the playlists in the playlist list but that is not implemented in this extension. As @badcel said it doesn't provide any means to display or interact with the content of a playlist. That's what the Tracklist interface is for. But much like the rest of the Mpris docs it's pretty vague about how it should behave when combined with the Playlist interface.

**Comment by JasonLG1979** [comment]
@eonpatapon Should be closed as invalid.

**Comment by i30817** [comment]
I switched to clementine anyway. Do what you want, because it's probably a upstream rythmbox bug anyway (since clementine works perfectly).

**Comment by JasonLG1979** [comment]
Did you even read what @badcel and I posted? This extension does not support the Tracklist interface. All the interfaces that it does support work as expected.

**Comment by i30817** [comment]
Sure i did. And since, i found that clementine doesn't show the original bug (since that was what the 1rst paragraph of the last response was about), i had meanwhile deleted the rythmbox source i used to test out the bug and switched to clementine. I'm just saying to not be surprised if someone opens a very similar bug report later, because in at least one datapoint (rythmbox, my computer) the workaround doesn't always work [as this post communicates.](https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/278#issuecomment-258727891)

**Comment by JasonLG1979** [comment]
Have you tested against the latest version of the extension?

**Comment by i30817** [comment]
Yes. Or latest as of two weeks ago anyway. Also a excuse me, i got confused, it was not the latest rythmbox code i used but the latest of the extension.

**Comment by JasonLG1979** [comment]
Unless you're testing on the latest code there's no way to tell if the bug has already been fixed, so the bug is invalid.

**Comment by JasonLG1979** [comment]
Just tested it in Fedora 25, GNOME 3.22, latest extension source, Rythmbox 3.4.1. Works perfectly.

**Comment by i30817** [comment]
Actually, you're right. Something changed in the last  25 days and i can no longer reproduce with updated extension code.

**Comment by JasonLG1979** [comment]
Well I'll have to file a bug with RB though. They aren't emitting the PlaylistChanged signal when they should. Which results in playlist names not updating in the extension when they are changed in RB. But that's a separate issue.

**Comment by JasonLG1979** [comment]
We're listening for it:
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/ad5f05d0fb6bbe5b9aa86bfdb085d4fe924741fe/src/player.js#L187-L189
