### ISSUE TITLE
[Feature Request] Disable the new Media Control Panel in notification tray

### ISSUE THREAD

**Issue by Eeveel** [eonpatapon/gnome-shell-extensions-mediaplayer#301]
Hi,
Is it possible to had the ability to disable the new Media control Panel (native in the new Gnome notification tray)? 

Thanks for you hard work!

**Comment by JasonLG1979** [comment]
Adding an option to do that is on my short todo list. Just got to figure out how or if it's even possible.

**Comment by JasonLG1979** [comment]
```js
Main.panel.statusArea.dateMenu._messageList._mediaSection.actor.hide();
```
Works to hide it. And to show it if it needs to be shown:

```js
let stockMpris = Main.panel.statusArea.dateMenu._messageList._mediaSection

if (stockMpris._shouldShow()) {
  stockMpris.actor.show();
}
```

**Comment by JasonLG1979** [comment]
Adding a user option should be pretty straight forward with the exception of hiding the setting for GNOME versions < 3.20.

**Comment by JasonLG1979** [comment]
It turns out it's a little trickier than I thought. Since it is never really disabled just hidden with hide(), It will try show it's self every time a new Mpris interface becomes available combine that with the habit of some players of exposing an empty interface initially for a split sec you end up with a situation where you're trying to hide it before it's shown. And it'll just show it's self later. I have worked around this by listening for the CanPlay prop change(the same prop the stock Mpris applet listens for to decide to show it's self) and after a very slight delay(250 ms) I check the setting and hide or show it accordingly. It seems to work. I'll test it for a few days.

**Comment by JasonLG1979** [comment]
![screenshot from 2016-12-15 01-38-11](https://cloud.githubusercontent.com/assets/6667703/21215492/36ac33be-c267-11e6-83ad-264d56a58833.png)

No built-in Mpris GNOME 3.22.

**Comment by JasonLG1979** [comment]
closed with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/300
