### ISSUE TITLE
Blacklist/Whitelist players

### ISSUE THREAD

**Issue by roizcorp** [eonpatapon/gnome-shell-extensions-mediaplayer#319]
perhaps raised before, I would like to define which players I could control with the tool

**Comment by JasonLG1979** [comment]
If they follow the MPRIS specs they will work if they don't they won't. We follow the spec and make a large effort to workaround broken implementations, but at the end of the day if a player does not work it is not our problem.

We don't do Whitelists. I'm working on implementing the TrackList interface and I have a Blacklist for that interface because GNOME Music's implementation is so broken that it crashes it's self.

**Comment by roizcorp** [comment]
the use case for this is that I use the indicator with MPD (via mpdrisv2), however whenever I play a simple audio (and perhaps video?) in VLC...it jumps into the indicator (and actually takes priority over the MPD)

**Comment by JasonLG1979** [comment]
The indicator focuses on whatever player sends a status message. If you don't want the above player disable mpris in vlc.

**Comment by roizcorp** [comment]
Thanks!
Do you know how by any chance?

**Comment by JasonLG1979** [comment]
Not off the top of my head. It would be under plugins maybe in the settings somewhere maybe?

**Comment by JasonLG1979** [comment]
I'm going to close this also.
